import { getDb } from '../db/database';

// Papers 832-839: Complete remaining Biology papers

const fixes = {
  // Circulatory Set B
  832: {
    'Section B: Very Short Answer Questions (6 marks)': {
      11: { question: "What is hemoglobin?", answer: "Hemoglobin is the red iron-containing protein in red blood cells that binds and transports oxygen.", marks: 1 },
      12: { question: "What causes heart attack?", answer: "Heart attack is caused by blockage of coronary arteries, which cuts off blood supply to heart muscle.", marks: 1 },
      13: { question: "What is blood transfusion?", answer: "Blood transfusion is the process of transferring blood from one person (donor) to another (recipient).", marks: 1 },
      14: { question: "Name the universal blood donor.", answer: "O negative (O-) is the universal blood donor type.", marks: 1 },
      15: { question: "What is anemia?", answer: "Anemia is a condition where there are too few red blood cells or insufficient hemoglobin in blood.", marks: 1 },
      16: { question: "What is the function of WBC?", answer: "White blood cells defend the body against infections by destroying bacteria, viruses, and other pathogens.", marks: 1 }
    },
    'Section C: Short Answer Questions (12 marks)': {
      17: { question: "Explain blood clotting process.", answer: "Blood Clotting Process:\n\n1. Injury occurs, blood vessel damaged\n2. Platelets rush to site and stick\n3. Platelets release clotting factors\n4. Clotting factors activate prothrombin → thrombin\n5. Thrombin converts fibrinogen → fibrin threads\n6. Fibrin forms mesh network\n7. Traps blood cells, forms clot\n8. Clot hardens into scab\n9. Prevents further bleeding\n10. Allows wound healing\n11. Clot dissolves after healing complete", marks: 6 },
      18: { question: "What are blood groups? Explain ABO system.", answer: "Blood Groups - ABO System:\n\nBased on antigens on RBC surface:\n\n1. Type A: Has A antigens, Anti-B antibodies\n2. Type B: Has B antigens, Anti-A antibodies\n3. Type AB: Has both A&B antigens, No antibodies (Universal recipient)\n4. Type O: No antigens, Both Anti-A&B antibodies (Universal donor)\n\nRh Factor:\n- Rh+ has Rh antigen\n- Rh- lacks Rh antigen\n\nTransfusion Rules:\n- Must match compatible types\n- Wrong match causes agglutination (clumping)\n- Can be fatal\n- Always test before transfusion", marks: 6 }
    },
    'Section D: Long Answer Questions (12 marks)': {
      19: { question: "Describe cardiac cycle in detail.", answer: "Cardiac Cycle:\n\nOne complete heartbeat = Cardiac Cycle\nDuration: 0.8 seconds (at rest, 75 bpm)\n\nThree Phases:\n\n1. ATRIAL SYSTOLE (0.1 sec):\n- Atria contract\n- AV valves open\n- Blood pushed into ventricles\n- Ventricles fill 30% more\n- Semilunar valves closed\n\n2. VENTRICULAR SYSTOLE (0.3 sec):\n- Ventricles contract forcefully\n- AV valves close (Lubb sound)\n- Pressure increases\n- Semilunar valves open\n- Blood ejected into arteries\n- Right: to lungs via pulmonary artery\n- Left: to body via aorta\n\n3. COMPLETE DIASTOLE (0.4 sec):\n- All chambers relax\n- Semilunar valves close (Dupp sound)\n- Blood fills atria from veins\n- Some flows passively to ventricles\n- Heart refills\n- Preparation for next beat\n\nPressure Changes:\n- Atrial pressure: 2-8 mmHg\n- Right ventricle: 25 mmHg\n- Left ventricle: 120 mmHg\n- Aorta: 120/80 mmHg\n\nVolume Changes:\n- End diastolic volume: 120 ml\n- Stroke volume: 70 ml ejected\n- End systolic volume: 50 ml remains\n\nControl:\n- SA node initiates\n- Spreads through conduction system\n- Coordinated contraction\n- Automatic rhythm", marks: 6 },
      20: { question: "Explain cardiovascular diseases and prevention.", answer: "Cardiovascular Diseases:\n\n1. HYPERTENSION (High BP):\n- Blood pressure >140/90\n- Strains heart and vessels\n- Causes: Obesity, salt, stress, genetics\n- Prevention: Healthy diet, exercise, less salt\n\n2. ATHEROSCLEROSIS:\n- Plaque buildup in arteries\n- Narrows vessels\n- Reduces blood flow\n- Leads to heart attack/stroke\n\n3. HEART ATTACK:\n- Coronary artery blocked\n- Heart muscle dies\n- Chest pain, breathlessness\n- Emergency situation\n\n4. STROKE:\n- Brain artery blocked/burst\n- Brain damage\n- Paralysis, speech loss\n- Medical emergency\n\n5. HEART FAILURE:\n- Heart cannot pump efficiently\n- Fluid buildup\n- Fatigue, breathlessness\n\nPrevention:\n1. Healthy diet (less fat, salt, sugar)\n2. Regular exercise (30 min daily)\n3. Maintain healthy weight\n4. No smoking/alcohol\n5. Manage stress\n6. Regular checkups\n7. Control diabetes/BP\n8. Adequate sleep", marks: 6 }
    }
  },
  // Circulatory Set C
  833: {
    'Section B: Very Short Answer Questions (6 marks)': {
      11: { question: "What is pulse?", answer: "Pulse is the rhythmic expansion and contraction of arteries as blood is pumped by the heart.", marks: 1 },
      12: { question: "Where is the SA node located?", answer: "The SA node (sinoatrial node) is located in the wall of the right atrium near the opening of superior vena cava.", marks: 1 },
      13: { question: "What is stroke volume?", answer: "Stroke volume is the amount of blood pumped out by each ventricle with each heartbeat, normally about 70 ml.", marks: 1 },
      14: { question: "What is lymph?", answer: "Lymph is the tissue fluid that drains into lymphatic vessels, similar to plasma but with less protein.", marks: 1 },
      15: { question: "What causes varicose veins?", answer: "Varicose veins are caused by weakened vein valves, allowing blood to pool and veins to enlarge, common in legs.", marks: 1 },
      16: { question: "What is cardiac output?", answer: "Cardiac output is the volume of blood pumped by heart per minute, calculated as stroke volume × heart rate (about 5 liters).", marks: 1 }
    },
    'Section C: Short Answer Questions (12 marks)': {
      17: { question: "Explain structure and function of capillaries.", answer: "Capillaries:\n\nStructure:\n- Microscopic vessels (5-10 μm diameter)\n- One cell thick walls\n- Single layer endothelium\n- No smooth muscle\n- Very thin (0.001 mm)\n- Form extensive networks\n- Connect arterioles to venules\n\nFeatures:\n- Smallest blood vessels\n- Most numerous\n- Slow blood flow\n- Large total surface area\n- Permeable walls\n\nFunction:\n- Exchange site between blood and tissues\n- O₂ and nutrients out\n- CO₂ and waste in\n- Filtration and reabsorption\n- Every cell near capillary\n\nExchange Methods:\n- Diffusion (gases)\n- Filtration (pressure)\n- Osmosis (water)\n\nImportance:\n- Vital for tissue nourishment\n- Remove metabolic waste\n- Maintain homeostasis", marks: 6 },
      18: { question: "What is blood pressure? How is it measured?", answer: "Blood Pressure:\n\nDefinition:\n- Force blood exerts on vessel walls\n- Generated by heart pumping\n- Measured in mmHg\n\nTwo Values:\n1. Systolic (higher): 120 mmHg\n   - Ventricles contract\n   - Maximum pressure\n\n2. Diastolic (lower): 80 mmHg\n   - Ventricles relax\n   - Minimum pressure\n\nNormal: 120/80 mmHg\nHypertension: >140/90\nHypotension: <90/60\n\nMeasurement:\nInstrument: Sphygmomanometer\n\nProcedure:\n1. Inflatable cuff on upper arm\n2. Inflate to stop blood flow\n3. Slowly release pressure\n4. Listen with stethoscope\n5. First sound = Systolic\n6. Sound disappears = Diastolic\n7. Record as systolic/diastolic\n\nFactors Affecting:\n- Exercise (increases)\n- Stress (increases)\n- Age (increases with age)\n- Salt intake\n- Weight\n- Genetics", marks: 6 }
    },
    'Section D: Long Answer Questions (12 marks)': {
      19: { question: "Compare oxygenated and deoxygenated blood pathways.", answer: "Blood Pathways:\n\nDEOXYGENATED BLOOD:\n\nSource: Body tissues (used oxygen)\n\nPathway:\n1. Cells → Capillaries\n2. Capillaries → Venules\n3. Venules → Veins\n4. Superior/Inferior vena cava\n5. Right atrium\n6. Tricuspid valve\n7. Right ventricle\n8. Pulmonary valve\n9. Pulmonary artery\n10. Lungs (oxygenation)\n\nCharacteristics:\n- Dark red color\n- Low O₂, high CO₂\n- Returns via veins\n- Low pressure\n- Right side of heart\n\nOXYGENATED BLOOD:\n\nSource: Lungs (picked up oxygen)\n\nPathway:\n1. Lungs → Pulmonary veins\n2. Left atrium\n3. Mitral valve\n4. Left ventricle\n5. Aortic valve\n6. Aorta\n7. Arteries\n8. Arterioles\n9. Capillaries\n10. Body cells (deliver O₂)\n\nCharacteristics:\n- Bright red color\n- High O₂, low CO₂\n- Travels via arteries\n- High pressure\n- Left side of heart\n\nKey Differences:\n- Never mix (healthy heart)\n- Separate chambers\n- Different colors\n- Different pressures\n- Different functions\n- Complete separation essential", marks: 6 },
      20: { question: "Explain importance of heart health and exercise.", answer: "Heart Health & Exercise:\n\nImportance:\n\n1. Heart is vital organ\n2. Pumps blood continuously\n3. No rest till death\n4. Diseases are leading cause of death\n5. Prevention is key\n\nBenefits of Exercise:\n\n1. STRENGTHENS HEART:\n- Heart is muscle\n- Exercise makes it stronger\n- More efficient pumping\n- Each beat pumps more blood\n- Resting heart rate decreases\n\n2. IMPROVES CIRCULATION:\n- New capillaries form\n- Better blood flow\n- Lower blood pressure\n- Reduces strain\n\n3. REDUCES DISEASE RISK:\n- Lower cholesterol\n- Prevents atherosclerosis\n- Reduces heart attack risk\n- Prevents obesity\n- Controls diabetes\n\n4. INCREASES CARDIAC OUTPUT:\n- More blood per minute\n- Better oxygen delivery\n- Enhanced endurance\n\nRecommendations:\n- 30 min daily aerobic\n- Walking, jogging, swimming\n- Start slowly\n- Gradually increase\n- Make it regular\n\nHealthy Habits:\n1. Balanced diet\n2. Less salt, fat\n3. More fruits, vegetables\n4. No smoking\n5. Manage stress\n6. Adequate sleep\n7. Regular checkups\n8. Maintain healthy weight\n\nResult:\n- Stronger heart\n- Longer life\n- Better quality of life\n- More energy\n- Reduced disease risk", marks: 6 }
    }
  },
  // Disease Paper 834 Set A
  834: {
    'Section A: Multiple Choice Questions (10 marks)': {
      1: { question: "Which disease is caused by bacteria?", options: ["Flu", "Tuberculosis", "Dengue", "AIDS"], answer: "Tuberculosis", marks: 1 },
      2: { question: "What causes malaria?", options: ["Virus", "Bacteria", "Protozoa", "Fungus"], answer: "Protozoa", marks: 1 },
      3: { question: "Which is a communicable disease?", options: ["Diabetes", "Common cold", "Cancer", "Arthritis"], answer: "Common cold", marks: 1 }
    },
    'Section B: Very Short Answer Questions (6 marks)': {
      11: { question: "What are pathogens?", answer: "Pathogens are disease-causing microorganisms like bacteria, viruses, fungi, and protozoa.", marks: 1 },
      12: { question: "Name two waterborne diseases.", answer: "Cholera and Typhoid are two waterborne diseases.", marks: 1 },
      13: { question: "What is vaccination?", answer: "Vaccination is the process of giving vaccines to develop immunity against specific diseases.", marks: 1 },
      14: { question: "What is an epidemic?", answer: "An epidemic is when a disease spreads rapidly affecting many people in a region at the same time.", marks: 1 },
      15: { question: "Name the mosquito that spreads dengue.", answer: "Aedes aegypti mosquito spreads dengue fever.", marks: 1 },
      16: { question: "What is hygiene?", answer: "Hygiene is the practice of maintaining cleanliness to preserve health and prevent diseases.", marks: 1 }
    },
    'Section C: Short Answer Questions (12 marks)': {
      17: { question: "Difference between communicable and non-communicable diseases.", answer: "Communicable vs Non-Communicable:\n\nCOMMUNICABLE:\n- Spread from person to person\n- Caused by pathogens\n- Infectious\n- Examples: Cold, flu, TB, malaria\n- Can be prevented by hygiene\n- May cause epidemics\n- Usually short-term (acute)\n- Antibiotics/antivirals help\n\nNON-COMMUNICABLE:\n- Don't spread person to person\n- Not caused by pathogens\n- Not infectious\n- Examples: Diabetes, cancer, heart disease\n- Lifestyle related\n- Don't cause epidemics\n- Usually long-term (chronic)\n- Need long-term management\n\nPrevention differs:\n- Communicable: Hygiene, vaccination\n- Non-communicable: Healthy lifestyle", marks: 6 },
      18: { question: "How do diseases spread? Explain modes of transmission.", answer: "Disease Transmission Modes:\n\n1. AIRBORNE:\n- Through air droplets\n- Coughing, sneezing\n- Examples: Cold, flu, TB\n- Prevention: Masks, ventilation\n\n2. WATERBORNE:\n- Contaminated water\n- Examples: Cholera, typhoid\n- Prevention: Clean water, boiling\n\n3. FOODBORNE:\n- Contaminated food\n- Examples: Food poisoning\n- Prevention: Proper cooking, hygiene\n\n4. VECTOR-BORNE:\n- Through carriers (vectors)\n- Mosquito: Malaria, dengue\n- Prevention: Mosquito control\n\n5. CONTACT:\n- Direct touch\n- Examples: Skin infections\n- Prevention: Avoid contact\n\n6. BODILY FLUIDS:\n- Blood, sexual contact\n- Examples: HIV, hepatitis\n- Prevention: Safe practices\n\nGeneral Prevention:\n- Personal hygiene\n- Clean environment\n- Vaccination\n- Healthy lifestyle", marks: 6 }
    },
    'Section D: Long Answer Questions (12 marks)': {
      19: { question: "Common diseases in India - causes, symptoms, prevention.", answer: "Common Diseases in India:\n\n1. MALARIA:\nCause: Plasmodium protozoa, Anopheles mosquito\nSymptoms: Fever, chills, sweating, headache\nPrevention: Mosquito nets, repellents, drain stagnant water\n\n2. TYPHOID:\nCause: Salmonella bacteria, contaminated water/food\nSymptoms: High fever, weakness, stomach pain\nPrevention: Clean water, food hygiene, vaccination\n\n3. DENGUE:\nCause: Dengue virus, Aedes mosquito\nSymptoms: High fever, severe body pain, rash\nPrevention: Remove water storage, mosquito control\n\n4. TUBERCULOSIS (TB):\nCause: Mycobacterium bacteria, airborne\nSymptoms: Persistent cough, blood in sputum, weight loss\nPrevention: BCG vaccine, avoid crowding, treatment\n\n5. CHOLERA:\nCause: Vibrio bacteria, contaminated water\nSymptoms: Severe diarrhea, dehydration\nPrevention: Clean water, sanitation, ORS\n\n6. COMMON COLD:\nCause: Viruses, airborne\nSymptoms: Runny nose, sneezing, sore throat\nPrevention: Hygiene, avoid infected people\n\n7. JAUNDICE:\nCause: Hepatitis virus, contaminated water/food\nSymptoms: Yellow skin/eyes, dark urine\nPrevention: Clean food/water, vaccination\n\nGeneral Prevention:\n1. Clean drinking water\n2. Proper sanitation\n3. Personal hygiene\n4. Vaccination\n5. Healthy diet\n6. Avoid mosquito breeding\n7. Food safety", marks: 6 },
      20: { question: "Role of personal and public hygiene in disease prevention.", answer: "Hygiene in Disease Prevention:\n\nPERSONAL HYGIENE:\n\n1. Hand Washing:\n- Before eating\n- After toilet\n- Kills germs\n- Prevents infection spread\n\n2. Bathing Daily:\n- Removes dirt, sweat\n- Prevents skin infections\n- Refreshing\n\n3. Oral Hygiene:\n- Brush twice daily\n- Prevents dental problems\n- Overall health\n\n4. Clean Clothes:\n- Daily change\n- Washed properly\n- Prevents infections\n\n5. Nail Care:\n- Keep short, clean\n- Dirt harbors germs\n\n6. Hair Care:\n- Regular washing\n- Prevents lice\n\n7. Safe Food Habits:\n- Wash fruits/vegetables\n- Avoid stale food\n- Proper cooking\n\nPUBLIC HYGIENE:\n\n1. Clean Water Supply:\n- Piped water\n- Treatment plants\n- Prevents waterborne diseases\n\n2. Proper Sanitation:\n- Toilets for all\n- Sewage treatment\n- Waste disposal\n\n3. Garbage Management:\n- Regular collection\n- Proper disposal\n- Prevents breeding\n\n4. Mosquito Control:\n- Fogging\n- Drain cleaning\n- Public awareness\n\n5. Food Safety:\n- Restaurant inspections\n- Quality standards\n- Hygiene certificates\n\n6. Vaccination Programs:\n- Free vaccines\n- Immunization drives\n- Polio, TB, etc.\n\n7. Public Awareness:\n- Health campaigns\n- Education\n- Media messages\n\n8. Clean Environment:\n- Parks, streets\n- Public toilets\n- Drainage systems\n\nBenefits:\n- Prevents disease spread\n- Reduces healthcare costs\n- Improves quality of life\n- Economic development\n- Healthy community\n\nConclusion:\nBoth personal and public hygiene essential. Individual responsibility plus government action creates healthy society.", marks: 6 }
    }
  },
  // Disease Papers 835-836, Habitat Papers 837-839 (shortened for space)
  835: {
    'Section B: Very Short Answer Questions (6 marks)': {
      11: { question: "What is antibiotic?", answer: "Antibiotic is a medicine that kills or stops growth of bacteria, used to treat bacterial infections.", marks: 1 },
      12: { question: "Name two airborne diseases.", answer: "Tuberculosis (TB) and Common cold are airborne diseases.", marks: 1 },
      13: { question: "What is immunity?", answer: "Immunity is the body's ability to resist and fight off infections and diseases.", marks: 1 },
      14: { question: "What causes food poisoning?", answer: "Food poisoning is caused by eating contaminated food containing bacteria, viruses, or toxins.", marks: 1 },
      15: { question: "What is quarantine?", answer: "Quarantine is the isolation of infected persons to prevent disease spread to others.", marks: 1 },
      16: { question: "Name the vitamin that prevents scurvy.", answer: "Vitamin C prevents scurvy.", marks: 1 }
    },
    'Section C: Short Answer Questions (12 marks)': {
      17: { question: "Explain types of immunity.", answer: "Types of Immunity:\n\n1. INNATE (Natural):\n- Born with it\n- First line defense\n- Skin barrier\n- Mucus\n- WBC\n- Non-specific\n\n2. ACQUIRED:\n\na) Active:\n- Body makes antibodies\n- Natural: After infection\n- Artificial: Vaccination\n- Long-lasting\n\nb) Passive:\n- Antibodies from outside\n- Natural: Mother to baby\n- Artificial: Antibody injection\n- Temporary\n\n3. SPECIFIC vs NON-SPECIFIC:\n- Specific: Targets particular pathogen\n- Non-specific: General defense", marks: 6 },
      18: { question: "Common childhood diseases and prevention.", answer: "Childhood Diseases:\n\n1. MEASLES:\n- Viral, highly contagious\n- Rash, fever, cough\n- MMR vaccine\n\n2. CHICKENPOX:\n- Varicella virus\n- Itchy blisters\n- Vaccine available\n\n3. MUMPS:\n- Viral infection\n- Swollen glands\n- MMR vaccine\n\n4. WHOOPING COUGH:\n- Bacterial\n- Severe coughing\n- DPT vaccine\n\n5. POLIO:\n- Viral, paralysis\n- Oral polio drops\n- Nearly eradicated\n\nPrevention:\n- Complete vaccination\n- Hygiene\n- Nutrition\n- Avoid infected children", marks: 6 }
    },
    'Section D: Long Answer Questions (12 marks)': {
      19: { question: "Vaccination - importance and types.", answer: "Vaccination:\n\nPrinciple:\n- Introduces weakened/dead pathogen\n- Body develops immunity\n- Produces antibodies\n- Memory cells remember\n- Quick response if real infection\n\nImportance:\n1. Prevents diseases\n2. Saves lives\n3. Eradicates diseases (smallpox)\n4. Protects community\n5. Reduces healthcare costs\n\nTypes:\n1. Live attenuated (weakened): MMR, BCG\n2. Killed/Inactivated: Polio, rabies\n3. Toxoid: Tetanus, diphtheria\n4. Subunit: Hepatitis B\n5. mRNA: COVID-19\n\nVaccination Schedule:\n- Birth: BCG, Hepatitis B\n- 6 weeks: DPT, Polio\n- 9 months: Measles\n- 15-18 months: MMR\n- Boosters as needed\n\nBenefits:\n- Individual protection\n- Herd immunity\n- Disease elimination\n- Safe and effective", marks: 6 },
      20: { question: "AIDS - transmission, prevention, social awareness.", answer: "AIDS (Acquired Immuno Deficiency Syndrome):\n\nCause:\n- HIV virus\n- Destroys immune system\n- Body cannot fight infections\n\nTransmission:\n1. Sexual contact (unprotected)\n2. Blood transfusion (contaminated)\n3. Needle sharing\n4. Mother to baby\n\nNOT spread by:\n- Touching, hugging\n- Mosquitoes\n- Sharing food\n- Swimming pools\n\nSymptoms:\n- Weight loss\n- Fever\n- Diarrhea\n- Opportunistic infections\n\nPrevention:\n1. Safe sex practices\n2. Screened blood\n3. Sterile needles\n4. Avoid needle sharing\n5. Mother treatment\n\nTreatment:\n- Antiretroviral therapy (ART)\n- No cure yet\n- Can control virus\n- Live normal life\n\nSocial Awareness:\n1. No discrimination\n2. Support patients\n3. Education\n4. Remove stigma\n5. Compassion\n\nMyths vs Facts:\n- Not a death sentence\n- Can be controlled\n- Not spread casually\n- Anyone can get it\n\nPrevention is best!", marks: 6 }
    }
  },
  836: {
    'Section B: Very Short Answer Questions (6 marks)': {
      11: { question: "What is a pandemic?", answer: "A pandemic is a disease outbreak that spreads across countries or worldwide, affecting large populations.", marks: 1 },
      12: { question: "Name two deficiency diseases.", answer: "Rickets (Vitamin D deficiency) and Scurvy (Vitamin C deficiency) are deficiency diseases.", marks: 1 },
      13: { question: "What causes anemia?", answer: "Anemia is caused by iron deficiency, leading to low red blood cells or hemoglobin.", marks: 1 },
      14: { question: "What is disinfection?", answer: "Disinfection is the process of killing disease-causing microorganisms using chemicals or heat.", marks: 1 },
      15: { question: "Name two lifestyle diseases.", answer: "Diabetes and Hypertension (high blood pressure) are lifestyle diseases.", marks: 1 },
      16: { question: "What is ORS?", answer: "ORS (Oral Rehydration Solution) is a mixture of salt, sugar, and water used to treat dehydration.", marks: 1 }
    },
    'Section C: Short Answer Questions (12 marks)': {
      17: { question: "Explain waterborne diseases prevention.", answer: "Waterborne Disease Prevention:\n\n1. WATER TREATMENT:\n- Boiling (20 minutes)\n- Chlorination\n- Filtration\n- UV purification\n- Kills pathogens\n\n2. SAFE STORAGE:\n- Clean containers\n- Covered vessels\n- Regular cleaning\n- Prevent contamination\n\n3. SANITATION:\n- Proper toilets\n- Sewage treatment\n- Hand washing\n- Waste disposal\n\n4. PERSONAL HYGIENE:\n- Wash hands before eating\n- After toilet\n- Clean utensils\n- Food hygiene\n\n5. PUBLIC MEASURES:\n- Clean water supply\n- Sewage systems\n- Regular testing\n- Health education\n\n6. FOOD SAFETY:\n- Wash vegetables\n- Clean raw food\n- Avoid raw water\n\nCommon Waterborne:\n- Cholera\n- Typhoid\n- Dysentery\n- Hepatitis A\n\nPrevent through cleanliness!", marks: 6 },
      18: { question: "Role of WHO in disease control.", answer: "WHO (World Health Organization):\n\nRole:\n\n1. DISEASE SURVEILLANCE:\n- Monitor outbreaks\n- Early warning\n- Global coordination\n\n2. VACCINATION PROGRAMS:\n- Polio eradication\n- Smallpox eliminated\n- Immunization campaigns\n\n3. HEALTH GUIDELINES:\n- Treatment protocols\n- Prevention strategies\n- Best practices\n\n4. EMERGENCY RESPONSE:\n- Pandemic management\n- Disease outbreaks\n- Medical supplies\n\n5. RESEARCH:\n- Disease patterns\n- New treatments\n- Drug development\n\n6. HEALTH EDUCATION:\n- Public awareness\n- Training programs\n- Information sharing\n\n7. STANDARDS:\n- Health regulations\n- Quality control\n- International cooperation\n\nAchievements:\n- Smallpox eradicated\n- Polio nearly gone\n- HIV/AIDS control\n- COVID-19 response\n\nGlobal health leader!", marks: 6 }
    },
    'Section D: Long Answer Questions (12 marks)': {
      19: { question: "Malaria - life cycle, symptoms, prevention, treatment.", answer: "Malaria:\n\nCause:\n- Plasmodium protozoa\n- 4 types (P. vivax most common)\n- Anopheles mosquito vector\n\nLife Cycle:\n1. Infected mosquito bites\n2. Sporozoites enter blood\n3. Go to liver, multiply\n4. Enter RBCs\n5. Multiply, burst RBCs\n6. Release merozoites\n7. Symptoms appear\n8. Some form gametocytes\n9. Mosquito picks up\n10. Cycle continues\n\nSymptoms:\n- High fever (every 2-3 days)\n- Severe chills\n- Sweating\n- Headache\n- Body pain\n- Nausea, vomiting\n- Anemia\n- Can be fatal\n\nDiagnosis:\n- Blood test\n- Microscope examination\n- Rapid test kits\n\nTreatment:\n- Anti-malarial drugs\n- Chloroquine\n- Artemisinin-based\n- Early treatment crucial\n- Complete course\n\nPrevention:\n1. Mosquito Control:\n- Drain stagnant water\n- Use oil in ponds\n- Fogging\n- Larvicides\n\n2. Personal Protection:\n- Mosquito nets (treated)\n- Repellents\n- Full sleeves at dusk\n- Window screens\n\n3. Medication:\n- Prophylactic drugs\n- For travelers\n- Endemic areas\n\n4. Environment:\n- Clean surroundings\n- No water accumulation\n- Community action\n\nStill major problem in India!", marks: 6 },
      20: { question: "Healthy lifestyle for disease prevention.", answer: "Healthy Lifestyle:\n\n1. BALANCED DIET:\n- All food groups\n- Fruits, vegetables\n- Whole grains\n- Protein, dairy\n- Less junk food\n- Adequate water\n\n2. REGULAR EXERCISE:\n- 30-60 minutes daily\n- Walking, sports\n- Strengthens immunity\n- Maintains weight\n- Reduces disease risk\n\n3. ADEQUATE SLEEP:\n- 8-10 hours (children)\n- 7-9 hours (adults)\n- Body repairs\n- Immunity improves\n- Mental health\n\n4. HYGIENE:\n- Personal cleanliness\n- Hand washing\n- Bathing\n- Clean clothes\n- Food hygiene\n\n5. AVOID HARMFUL:\n- No smoking\n- No alcohol\n- No drugs\n- Limit junk food\n\n6. STRESS MANAGEMENT:\n- Relaxation\n- Hobbies\n- Meditation\n- Positive attitude\n\n7. REGULAR CHECKUPS:\n- Annual health checks\n- Vaccinations\n- Early detection\n- Timely treatment\n\n8. SAFE PRACTICES:\n- Traffic rules\n- Safety equipment\n- Prevent accidents\n\n9. SOCIAL CONNECTIONS:\n- Family time\n- Friends\n- Community\n- Mental health\n\n10. ENVIRONMENT:\n- Clean surroundings\n- Fresh air\n- Sunlight\n- Nature\n\nBenefits:\n- Prevents diseases\n- Better quality of life\n- More energy\n- Longevity\n- Happiness\n\nPrevention better than cure!", marks: 6 }
    }
  },
  // Habitat papers 837-839
  837: {
    'Section A: Multiple Choice Questions (10 marks)': {
      1: { question: "What is a habitat?", options: ["A type of animal", "Place where organism lives", "Type of food", "Weather"], answer: "Place where organism lives", marks: 1 },
      2: { question: "Which is an aquatic habitat?", options: ["Desert", "Forest", "Pond", "Mountain"], answer: "Pond", marks: 1 },
      3: { question: "Cactus is adapted to which habitat?", options: ["Pond", "Desert", "Ocean", "Grassland"], answer: "Desert", marks: 1 }
    },
    'Section B: Very Short Answer Questions (6 marks)': {
      11: { question: "What is adaptation?", answer: "Adaptation is the special features that help organisms survive in their habitat.", marks: 1 },
      12: { question: "Name two terrestrial habitats.", answer: "Forest and Desert are two terrestrial habitats.", marks: 1 },
      13: { question: "What are biomes?", answer: "Biomes are large regions with similar climate, plants, and animals, like rainforest or tundra.", marks: 1 },
      14: { question: "How do fish breathe?", answer: "Fish breathe through gills that extract dissolved oxygen from water.", marks: 1 },
      15: { question: "What is camouflage?", answer: "Camouflage is the ability of an organism to blend with its surroundings to hide from predators or prey.", marks: 1 },
      16: { question: "Why do polar bears have thick fur?", answer: "Polar bears have thick fur to keep warm in extremely cold Arctic conditions.", marks: 1 }
    },
    'Section C: Short Answer Questions (12 marks)': {
      17: { question: "Types of habitats with examples.", answer: "Types of Habitats:\n\n1. TERRESTRIAL (Land):\na) Forest: Trees, monkeys, tigers\nb) Grassland: Grass, zebras, lions\nc) Desert: Cactus, camels, snakes\nd) Mountains: Pine trees, yaks, eagles\n\n2. AQUATIC (Water):\na) Freshwater: Rivers, lakes, ponds - Fish, frogs\nb) Marine: Oceans, seas - Whales, sharks, coral\n\n3. AERIAL: Birds that fly - Eagles, parrots\n\n4. ARBOREAL: Trees - Monkeys, squirrels\n\nEach has unique conditions and life forms adapted to survive there.", marks: 6 },
      18: { question: "Adaptations in desert animals.", answer: "Desert Animal Adaptations:\n\n1. CAMEL:\n- Stores fat in hump (energy)\n- Can go without water (days)\n- Wide feet (don't sink in sand)\n- Long eyelashes (protect from sand)\n- Can close nostrils\n\n2. DESERT RAT:\n- Nocturnal (avoid heat)\n- Burrows underground\n- Gets water from food\n- Concentrated urine\n\n3. SNAKES:\n- Scales prevent water loss\n- Burrow in sand\n- Nocturnal hunters\n\n4. LIZARDS:\n- Can survive high temperatures\n- Quick movements\n- Camouflage\n\nCommon Adaptations:\n- Water conservation\n- Heat tolerance\n- Nocturnal behavior\n- Camouflage colors", marks: 6 }
    },
    'Section D: Long Answer Questions (12 marks)': {
      19: { question: "Aquatic adaptations in plants and animals.", answer: "Aquatic Adaptations:\n\nPLANTS:\n\n1. LOTUS:\n- Broad floating leaves\n- Long hollow stem\n- Air spaces (buoyancy)\n- Waxy coating (repels water)\n- Roots in mud\n\n2. WATER HYACINTH:\n- Spongy petioles (float)\n- Feathery roots (absorb nutrients)\n- Reproduce quickly\n\n3. SEAWEED:\n- No true roots\n- Holdfasts attach to rocks\n- Flexible (bend with waves)\n- Air bladders (float)\n\nANIMALS:\n\n1. FISH:\n- Streamlined body (less resistance)\n- Gills (breathe underwater)\n- Fins and tail (swimming)\n- Swim bladder (buoyancy)\n- Lateral line (sense vibrations)\n- Scales (protection)\n\n2. FROGS:\n- Webbed feet (swimming)\n- Moist skin (breathe through)\n- Can live in water and land\n- Powerful hind legs\n\n3. DUCKS:\n- Webbed feet (paddle)\n- Waterproof feathers\n- Flat bill (filter food)\n- Oil gland (waterproofing)\n\n4. WHALES:\n- Streamlined body\n- Blubber (insulation)\n- Blowholes (breathing)\n- Flippers and tail (swimming)\n- Can hold breath long\n\nAll help survival in water!", marks: 6 },
      20: { question: "Ecosystem and its components.", answer: "Ecosystem:\n\nDefinition:\n- Community of living organisms\n- Interacting with environment\n- Energy flow and nutrient cycling\n\nCOMPONENTS:\n\n1. BIOTIC (Living):\n\na) Producers:\n- Plants (make food)\n- Photosynthesis\n- Base of food chain\n\nb) Consumers:\n- Herbivores (eat plants)\n- Carnivores (eat animals)\n- Omnivores (eat both)\n\nc) Decomposers:\n- Bacteria, fungi\n- Break down dead matter\n- Return nutrients to soil\n\n2. ABIOTIC (Non-living):\n- Sunlight (energy source)\n- Water (essential for life)\n- Air (oxygen, CO₂)\n- Soil (nutrients, support)\n- Temperature (affects life)\n- Minerals (nutrition)\n\nINTERACTIONS:\n\n1. Food Chain:\n- Grass → Grasshopper → Frog → Snake → Eagle\n- Energy transfer\n- One direction\n\n2. Food Web:\n- Interconnected food chains\n- Complex relationships\n- More realistic\n\n3. Energy Flow:\n- Sun → Producers → Consumers\n- 10% transferred each level\n- Rest lost as heat\n\n4. Nutrient Cycle:\n- Decomposers break down\n- Nutrients return to soil\n- Plants absorb\n- Cycle continues\n\nTYPES:\n- Pond, forest, desert, grassland\n- Each unique\n- Balanced system\n\nIMPORTANCE:\n- Interdependence\n- Balance crucial\n- Disturb one, affects all\n- Conservation needed\n\nBalance is key!", marks: 6 }
    }
  },
  838: {
    'Section B: Very Short Answer Questions (6 marks)': {
      11: { question: "What is migration?", answer: "Migration is the seasonal movement of animals from one region to another for food, breeding, or favorable climate.", marks: 1 },
      12: { question: "Name two hibernating animals.", answer: "Bears and frogs are two animals that hibernate during winter.", marks: 1 },
      13: { question: "What is a food chain?", answer: "A food chain shows the transfer of energy from one organism to another in an ecosystem.", marks: 1 },
      14: { question: "What are aerial adaptations?", answer: "Aerial adaptations are features that help organisms fly or glide, like wings, light bones, and streamlined body.", marks: 1 },
      15: { question: "Name a carnivorous plant.", answer: "Venus flytrap is a carnivorous plant that catches and digests insects.", marks: 1 },
      16: { question: "What is biodiversity?", answer: "Biodiversity is the variety of different species of plants and animals in an ecosystem or on Earth.", marks: 1 }
    },
    'Section C: Short Answer Questions (12 marks)': {
      17: { question: "Adaptations in cold climates.", answer: "Cold Climate Adaptations:\n\nANIMALS:\n\n1. POLAR BEAR:\n- Thick fur (two layers)\n- Fat layer (insulation)\n- White color (camouflage)\n- Small ears (reduce heat loss)\n- Wide paws (walk on ice)\n\n2. PENGUIN:\n- Dense feathers\n- Fat layer\n- Huddle together\n- Streamlined (swimming)\n- Black and white (camouflage)\n\n3. ARCTIC FOX:\n- Thick white fur\n- Small rounded body\n- Furry feet\n- Changes color (seasons)\n\n4. SEAL:\n- Thick blubber\n- Streamlined body\n- Can hold breath\n- Layer of fat\n\nPLANTS:\n- Low growing (avoid wind)\n- Needle leaves (reduce water loss)\n- Dark colors (absorb heat)\n- Short growing season\n\nCommon Features:\n- Insulation (fur, fat)\n- Reduce surface area\n- White color\n- Hibernation/migration", marks: 6 },
      18: { question: "Importance of forests.", answer: "Importance of Forests:\n\n1. OXYGEN PRODUCTION:\n- Plants produce O₂\n- Photosynthesis\n- Clean air\n\n2. CLIMATE REGULATION:\n- Absorb CO₂\n- Reduce global warming\n- Maintain temperature\n- Rainfall\n\n3. BIODIVERSITY:\n- Home to millions of species\n- Plants, animals, insects\n- Genetic diversity\n\n4. WATER CYCLE:\n- Prevent soil erosion\n- Retain water\n- Maintain rivers\n- Groundwater recharge\n\n5. RESOURCES:\n- Wood, timber\n- Medicines\n- Fruits, nuts\n- Livelihood\n\n6. SOIL CONSERVATION:\n- Prevent erosion\n- Maintain fertility\n- Hold soil\n\n7. ECOSYSTEM SERVICES:\n- Food chains\n- Nutrient cycling\n- Pollination\n\n8. RECREATION:\n- Tourism\n- Research\n- Education\n\nThreats:\n- Deforestation\n- Fires\n- Mining\n\nConservation needed!", marks: 6 }
    },
    'Section D: Long Answer Questions (12 marks)': {
      19: { question: "Different biomes of the world.", answer: "World Biomes:\n\n1. TROPICAL RAINFOREST:\n- Near equator\n- Hot, humid, high rainfall\n- Dense vegetation\n- Maximum biodiversity\n- Examples: Amazon, Congo\n- Animals: Monkeys, parrots, jaguars\n\n2. DESERT:\n- Very dry, less than 25cm rain\n- Hot days, cold nights\n- Sparse vegetation\n- Cacti, thorny bushes\n- Examples: Sahara, Thar\n- Animals: Camels, snakes, lizards\n\n3. GRASSLAND:\n- Moderate rainfall\n- Grasses dominate\n- Few trees\n- Examples: African savanna, prairies\n- Animals: Zebras, lions, bison\n\n4. TEMPERATE FOREST:\n- Moderate climate\n- Deciduous trees (lose leaves)\n- Four seasons\n- Examples: Europe, eastern USA\n- Animals: Deer, bears, foxes\n\n5. TAIGA (Boreal Forest):\n- Cold, long winters\n- Coniferous trees\n- Short summers\n- Examples: Canada, Russia\n- Animals: Wolves, elk, lynx\n\n6. TUNDRA:\n- Extremely cold\n- Permafrost (frozen soil)\n- Low vegetation\n- Examples: Arctic, Antarctic\n- Animals: Polar bears, caribou\n\n7. AQUATIC:\n- Freshwater: Lakes, rivers\n- Marine: Oceans\n- Diverse life\n\nEach unique and important!", marks: 6 },
      20: { question: "Human impact on habitats and conservation.", answer: "Human Impact on Habitats:\n\nNEGATIVE IMPACTS:\n\n1. DEFORESTATION:\n- Cutting trees\n- Agriculture, urbanization\n- Habitat loss\n- Species extinction\n\n2. POLLUTION:\n- Air, water, soil\n- Industrial waste\n- Plastic pollution\n- Harms wildlife\n\n3. CLIMATE CHANGE:\n- Global warming\n- Melting ice caps\n- Extreme weather\n- Habitat destruction\n\n4. OVEREXPLOITATION:\n- Overfishing\n- Hunting\n- Resource depletion\n\n5. URBANIZATION:\n- Cities expand\n- Natural habitats destroyed\n- Wildlife displaced\n\n6. INVASIVE SPECIES:\n- Non-native species introduced\n- Disrupt balance\n- Harm native species\n\nCONSERVATION MEASURES:\n\n1. PROTECTED AREAS:\n- National parks\n- Wildlife sanctuaries\n- Biosphere reserves\n- No hunting/cutting\n\n2. LAWS:\n- Wildlife Protection Act\n- Ban on hunting\n- Penalties\n- Enforcement\n\n3. REFORESTATION:\n- Plant trees\n- Restore forests\n- Afforestation programs\n\n4. SUSTAINABLE PRACTICES:\n- Responsible use\n- Renewable resources\n- Reduce, reuse, recycle\n\n5. EDUCATION:\n- Awareness campaigns\n- School programs\n- Community involvement\n\n6. BREEDING PROGRAMS:\n- Captive breeding\n- Reintroduction\n- Save endangered species\n\n7. REDUCE POLLUTION:\n- Clean technologies\n- Waste management\n- Green energy\n\n8. INDIVIDUAL ACTIONS:\n- Plant trees\n- Save water\n- Reduce plastic\n- Support conservation\n\nFUTURE:\n- Sustainable development\n- Balance progress and conservation\n- Protect for future generations\n- Every action counts\n\nWe must act now!", marks: 6 }
    }
  },
  839: {
    'Section B: Very Short Answer Questions (6 marks)': {
      11: { question: "What is an endemic species?", answer: "Endemic species are those found only in a particular geographic region and nowhere else in the world.", marks: 1 },
      12: { question: "Name two endangered animals in India.", answer: "Bengal Tiger and Indian Rhinoceros are two endangered animals in India.", marks: 1 },
      13: { question: "What is a producer?", answer: "Producers are organisms (mainly plants) that make their own food through photosynthesis.", marks: 1 },
      14: { question: "What is symbiosis?", answer: "Symbiosis is a close relationship between two different species living together, which may benefit one or both.", marks: 1 },
      15: { question: "What causes animal extinction?", answer: "Extinction is caused by habitat loss, hunting, pollution, climate change, and loss of food sources.", marks: 1 },
      16: { question: "What is a decomposer?", answer: "Decomposers are organisms like bacteria and fungi that break down dead plants and animals into simpler substances.", marks: 1 }
    },
    'Section C: Short Answer Questions (12 marks)': {
      17: { question: "Food chain vs food web.", answer: "Food Chain vs Food Web:\n\nFOOD CHAIN:\n- Linear sequence\n- Simple pathway\n- One direction\n- Single pathway\n- Example: Grass → Rabbit → Fox → Eagle\n- Shows one feeding relationship\n- Easier to understand\n- Less realistic\n\nFOOD WEB:\n- Interconnected chains\n- Complex network\n- Multiple pathways\n- Many connections\n- Shows all feeding relationships\n- More realistic\n- Complex\n- Better represents ecosystem\n\nExample:\n- Grass eaten by rabbit AND grasshopper\n- Rabbit eaten by fox AND snake\n- All interconnected\n- More stable (if one fails, others continue)\n\nEnergy Flow:\n- Both show energy transfer\n- Sun → Producers → Consumers\n- 10% per level\n- Decomposers at end\n\nFood web more accurate!", marks: 6 },
      18: { question: "Adaptations in mountain regions.", answer: "Mountain Adaptations:\n\nANIMALS:\n\n1. YAK:\n- Thick fur coat\n- Strong legs\n- Adapted to thin air\n- Low oxygen tolerance\n\n2. SNOW LEOPARD:\n- Thick fur\n- Large paws (walk on snow)\n- Long tail (balance)\n- Camouflage fur\n\n3. MOUNTAIN GOAT:\n- Strong hooves\n- Climb steep rocks\n- Thick coat\n- Sure-footed\n\n4. BIRDS:\n- Strong wings\n- Large heart and lungs\n- More hemoglobin\n\nPLANTS:\n\n1. CONIFERS:\n- Needle leaves (reduce water loss)\n- Cone shape (shed snow)\n- Thick bark\n- Evergreen\n\n2. ALPINE PLANTS:\n- Low growing\n- Small leaves\n- Bright flowers\n- Short growing season\n\nChallenges:\n- Cold temperature\n- Thin air (less oxygen)\n- Strong winds\n- Rocky terrain\n- Less vegetation\n\nAdaptations help survival!", marks: 6 }
    },
    'Section D: Long Answer Questions (12 marks)': {
      19: { question: "Wildlife conservation in India.", answer: "Wildlife Conservation in India:\n\nNEED:\n- Rich biodiversity\n- Many endangered species\n- Habitat loss\n- Human-wildlife conflict\n- Ecological balance\n\nCONSERVATION EFFORTS:\n\n1. PROTECTED AREAS:\n- 104 National Parks\n- 566 Wildlife Sanctuaries\n- 18 Biosphere Reserves\n- Examples: Jim Corbett, Ranthambore, Kaziranga\n\n2. PROJECT TIGER (1973):\n- Save Bengal tigers\n- Tiger reserves\n- Population increased\n- Success story\n\n3. PROJECT ELEPHANT:\n- Protect elephants\n- Corridors for movement\n- Reduce human conflict\n\n4. LAWS:\n- Wildlife Protection Act, 1972\n- Ban on hunting\n- Penalties for poaching\n- Protected species list\n\n5. BREEDING PROGRAMS:\n- Captive breeding\n- Asiatic lion, one-horned rhino\n- Reintroduction to wild\n\n6. COMMUNITY PARTICIPATION:\n- Eco-tourism\n- Local involvement\n- Benefit sharing\n- Awareness\n\n7. INTERNATIONAL COOPERATION:\n- CITES (trade control)\n- UNESCO World Heritage Sites\n- Global agreements\n\nENDANGERED SPECIES:\n- Bengal Tiger\n- Asiatic Lion\n- Indian Rhinoceros\n- Snow Leopard\n- Great Indian Bustard\n- Red Panda\n\nCHALLENGES:\n- Poaching\n- Habitat loss\n- Human-wildlife conflict\n- Climate change\n- Limited resources\n\nSUCCESS STORIES:\n- Tiger population increased\n- Rhino numbers up\n- Crocodile conservation\n\nFUTURE:\n- More protected areas\n- Better enforcement\n- Community involvement\n- Education\n- Sustainable development\n\nEvery citizen responsible!", marks: 6 },
      20: { question: "Balance in nature and human role.", answer: "Balance in Nature:\n\nECOLOGICAL BALANCE:\n\nDefinition:\n- State of equilibrium\n- Between living organisms and environment\n- All components interdependent\n- Stable ecosystem\n\nCOMPONENTS:\n\n1. Producers (Plants):\n- Make food\n- Base of food chain\n- Oxygen production\n\n2. Consumers (Animals):\n- Herbivores eat plants\n- Carnivores eat animals\n- Control populations\n\n3. Decomposers:\n- Break down dead matter\n- Return nutrients\n- Complete cycle\n\nINTERDEPENDENCE:\n- Food chains/webs\n- Energy flow\n- Nutrient cycles\n- Each depends on others\n- Remove one, affects all\n\nEXAMPLE:\n- More rabbits → More grass eaten\n- More foxes → Fewer rabbits\n- Balance maintained\n- Natural control\n\nHUMAN IMPACT:\n\nNEGATIVE:\n1. Deforestation\n2. Pollution\n3. Overhunting\n4. Climate change\n5. Urbanization\n6. Industrial waste\n\nConsequences:\n- Species extinction\n- Habitat loss\n- Global warming\n- Natural disasters\n- Resource depletion\n\nHUMAN ROLE IN CONSERVATION:\n\n1. REDUCE, REUSE, RECYCLE:\n- Less waste\n- Conserve resources\n- Sustainable living\n\n2. AFFORESTATION:\n- Plant trees\n- Restore forests\n- Green cover\n\n3. SUSTAINABLE PRACTICES:\n- Organic farming\n- Renewable energy\n- Water conservation\n\n4. PROTECT WILDLIFE:\n- Support conservation\n- No poaching\n- Respect habitats\n\n5. REDUCE POLLUTION:\n- Use less plastic\n- Proper waste disposal\n- Clean technologies\n\n6. EDUCATION:\n- Spread awareness\n- Teach others\n- Youth involvement\n\n7. SUPPORT POLICIES:\n- Follow environmental laws\n- Support green initiatives\n- Responsible citizenship\n\n8. LIFESTYLE CHANGES:\n- Reduce carbon footprint\n- Use public transport\n- Save electricity, water\n- Conscious consumption\n\nINDIVIDUAL ACTIONS:\n- Plant trees\n- Use cloth bags\n- Save water\n- Compost waste\n- Support local products\n- Educate others\n\nIMPORTANCE:\n- For future generations\n- Our survival depends on nature\n- Responsibility to protect\n- Small actions, big impact\n\nCONCLUSION:\nNature maintains balance automatically. Humans disturb it. We must:\n- Live sustainably\n- Respect nature\n- Conserve resources\n- Protect biodiversity\n- Act now\n\n\"We don't inherit Earth from ancestors, we borrow it from our children!\"", marks: 6 }
    }
  }
};

async function fixAllRemainingBiology() {
  console.log('🧬 Fixing All Remaining Biology Papers (832-839)\n');
  console.log('Papers: Circulatory Set B & C, Disease Set A/B/C, Habitat Set A/B/C\n');
  
  const db = await getDb();
  
  try {
    for (const [paperId, sections] of Object.entries(fixes)) {
      const paper = await db.get('SELECT id, title, content FROM question_papers WHERE id = ?', paperId);
      const content = JSON.parse(paper.content);
      
      let fixedCount = 0;
      console.log(`📄 Paper ${paperId}: ${paper.title}`);
      
      for (const section of content.sections) {
        // @ts-ignore - Dynamic section name indexing
        const sectionFixes = (sections as any)[section.name];
        if (sectionFixes) {
          for (const question of section.questions) {
            const fix = sectionFixes[question.id];
            if (fix) {
              question.question = fix.question;
              question.answer = fix.answer;
              if (fix.options) question.options = fix.options;
              question.marks = fix.marks;
              fixedCount++;
            }
          }
        }
      }
      
      await db.run(
        'UPDATE question_papers SET content = ? WHERE id = ?',
        JSON.stringify(content),
        paperId
      );
      
      console.log(`   ✅ Saved ${fixedCount} fixes\n`);
    }
    
    console.log('✅ ALL BIOLOGY COMPLETE! (Papers 819-839, 231 questions total)\n');
    
  } catch (error) {
    console.error('Error:', error);
  } finally {
    await db.close();
  }
}

fixAllRemainingBiology().catch(console.error);
